#!/usr/bin/env python3
import glob
import os

for module in glob.iglob('libPyKAN/*.py'):
    if not 'doctest' in open(module).read():
        print('%s does not have doctests implemented. Skipping' %module)
        continue
    else:
        print("Testing %s  " %module, end=' ')
        #I know os.system is not the prefered way these days but it's fine for this purpose
        if os.system('python %s' %module):
            print(" - Error - %s has failed it's tests !!!" %module)
        else:
            print(" -  Passed.")

